# Generated by Django 3.1.7 on 2021-03-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebp', '0002_exercise_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
