# Generated by Django 3.1.7 on 2021-03-06 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebp', '0004_auto_20210306_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('file', models.FileField(upload_to='exercise')),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 6, 21, 17, 26, 374227))),
                ('vote', models.IntegerField()),
            ],
        ),
    ]
