# Generated by Django 3.1.7 on 2021-03-07 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebp', '0007_auto_20210307_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 17, 25, 17, 83165)),
        ),
    ]
