# Generated by Django 3.1.7 on 2021-03-07 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebp', '0008_auto_20210307_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 18, 54, 45, 603530)),
        ),
    ]
